# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        EscritorBundle\Entity\DwUser: plaintext

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        main:
            entity: { class: EscritorBundle\Entity\DwUser, property: username }


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs

        secured_area:
            pattern:    ^/
            anonymous: ~


            form_login:
                login_path:  login
                check_path:  login

            logout:
                path: /logout
                target: /admin



    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/admin, roles: ROLE_ADMIN }

